#pragma once

enum MESSAGE_CODES { 
	SIGN_UP = 10,
	LOG_IN = 11,
	LOG_OUT = 12,
	GET_ROOMS = 13,
	GET_PLAYERS_IN_ROOM = 14,
	JOIN_ROOM = 15,
	CREATE_ROOM = 16,
	HIGH_SCORE = 17,
	GET_STATISTICS = 18
};

enum STATUSES {
	FAILURE,
	SUCCESS,
	INCORRECT_PASSWORD,
	USER_DOES_NOT_EXIST,
	USER_ALREADY_EXISTS,
	USER_ALREADY_LOGGED_IN,
	USER_ALREADY_IN_ROOM,
};